server:
  port:
    9091



spring:
  mvc:
    servlet:
      load-on-startup: 1
    static-path-pattern: /**
  application:
    name: rest-app

  datasource:
    url: jdbc:postgresql://localhost:5432/TestProject
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect



user:
  min-age: 18